name: Build
on:
  workflow_call:
    inputs:
      env-type: 
        required: true
        type: string
        default: None
      hw-type:
        required: true
        type: string
        default: None

jobs:
  # build-docker:
  #   name: Build Docker (${{ inputs.env-type }}.${{ inputs.hw-type }})
  #   if: inputs.env-type == 'docker'
  #   runs-on: ubuntu-latest
  #   container: devjiu/cpu-hdk:check

  #   # output:
  #   #   out-id: out.${{ inputs.env-type }}.${{ inputs.hw-type }}

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Test
  #       run: |
  #         echo "env: " ${{ inputs.env-type }}
  #         echo "hw: " ${{ inputs.hw-type }}
  #         ls -la
  #         g++ main.cpp
  # build-conda: 
  #   name: Build Conda (${{ inputs.env-type }}.${{ inputs.hw-type }})
  #   if: inputs.env-type == 'conda'
  #   runs-on: ubuntu-latest

  #   # output:
  #   #   out-id: out.${{ inputs.env-type }}.${{ inputs.hw-type }}

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Test
  #       run: |
  #         echo "env: " ${{ inputs.env-type }}
  #         echo "hw: " ${{ inputs.hw-type }}
  #         ls -la
  #         g++ main.cpp
  build-common:
    name: Build common (${{ inputs.env-type }}.${{ inputs.hw-type }})
    runs-on: ubuntu-latest

    # output:
    #   out-id: out.${{ inputs.env-type }}.${{ inputs.hw-type }}

    steps:
      - if: inputs.env-type == 'docker'
        run: |
          docker pull devjiu/cpu-hdk:check
      - if: inputs.env-type == 'docker'
        uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      
      - uses: actions/checkout@v3

      - if: inputs.env-type == 'docker'
        run: |
          docker run --rm -i \
            -v ${PWD}:/home/hdk \
            -w /home/hdk \
            devjiu/cpu-hdk:check \
            /usr/bin/bash -c \
            "/usr/bin/bash && ls -la ../"
      

      - name: Test
        run: |
          echo "env: " ${{ inputs.env-type }}
          echo "hw: " ${{ inputs.hw-type }}
          ls -la ../
          g++ main.cpp