name: Build
on:
  workflow_call:
    inputs:
      env-type: 
        required: true
        type: string
        default: None
      hw-type:
        required: true
        type: string
        default: None

jobs:
  build:
    name: Build (${{ inputs.env-type }}.${{ inputs.hw-type }})
    runs-on: ubuntu-latest
    if: ${{ inputs.env-type }} == docker
    container: devjiu/cpu-hdk:check

    # output:
    #   out-id: out.${{ inputs.env-type }}.${{ inputs.hw-type }}

    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |
          echo "env: " ${{ inputs.env-type }}
          echo "hw: " ${{ inputs.hw-type }}
          ls -la
          g++ main.cpp