name: Build
on:
  workflow_call:
    inputs:
      env-type: 
        required: true
        default: None
      hw-type:
        required: true
        default: None

jobs:
  build:
    name: Build (${{ matrix.env-type }}.${{ matrix.hw-type }})
    runs-on: ubuntu-latest
    container: devjiu/cpu-hdk:check

    output:
      out-id: out.${{ matrix.env-type }}.${{ matrix.hw-type }}

    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |
          echo "env: " ${{ matrix.env-type }}
          echo "hw: " ${{ matrix.hw-type }}
          ls -la
          g++ main.cpp