name: Build
on:
  workflow_call:
    inputs:
      env-type: 
        required: true
        type: string
        default: None
      hw-type:
        required: true
        type: string
        default: None

jobs:
  build-common:
    name: Build (${{ inputs.env-type }}.${{ inputs.hw-type }})
    runs-on: ubuntu-latest

    env: 
      DOCKER_OPTS: " -g  /tmp/docker-registry"

    steps:
      - run: |
          export DOCKER_OPTS=" -g  /tmp/docker-registry"
          sudo ls -la /var/lib/docker
          docker image ls -a
      - if: inputs.env-type == 'docker'
        uses: actions/cache@v3
        with:
          path: /tmp/docker-registry
          key: image-cached
          restore-keys: image-cached
      - if: inputs.env-type == 'docker'
        run: |
          DOCKER_OPTS=" -g  /tmp/docker-registry" && sudo systemctl restart docker
          sudo ln -sfv /tmp/docker-registry /var/lib/docker
          docker pull devjiu/cpu-hdk:check || true
          docker image ls -a 
      - run: |
          echo "cache-hit? \"${{ steps.cache.outputs.cache-hit }}\""
      - if: inputs.env-type == 'docker'
        run: |
          docker run -i --name verify\
            -v ${PWD}:/home/hdk \
            -w /home/hdk \
            devjiu/cpu-hdk:check \
            /usr/bin/bash
          docker image ls -a
          docker container ls -a
          docker start verify
          echo "PRE=docker exec verify" >> $GITHUB_ENV

      - uses: actions/checkout@v3

      - run: |
          ${{env.PRE}} echo "env: " ${{ inputs.env-type }}
          ${{env.PRE}} echo "hw: " ${{ inputs.hw-type }}
          ${{env.PRE}} ls -la ../
          # ${{env.PRE}} g++ main.cpp

  call-test:
    needs: [build-common]
    strategy:
      matrix:
        test-type: [unit, integration]
    uses: ./.github/workflows/ex_test.yml
    with:
      test-type: ${{ matrix.test-type }}
      env-type: ${{ inputs.env-type }}
      hw-type: ${{ inputs.hw-type }}