name: Build
on:
  workflow_call:
    inputs:
      env-type: 
        required: true
        type: string
        default: None
      hw-type:
        required: true
        type: string
        default: None

jobs:
  # build-docker:
  #   name: Build Docker (${{ inputs.env-type }}.${{ inputs.hw-type }})
  #   if: inputs.env-type == 'docker'
  #   runs-on: ubuntu-latest
  #   container: devjiu/cpu-hdk:check

  #   # output:
  #   #   out-id: out.${{ inputs.env-type }}.${{ inputs.hw-type }}

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Test
  #       run: |
  #         echo "env: " ${{ inputs.env-type }}
  #         echo "hw: " ${{ inputs.hw-type }}
  #         ls -la
  #         g++ main.cpp
  # build-conda: 
  #   name: Build Conda (${{ inputs.env-type }}.${{ inputs.hw-type }})
  #   if: inputs.env-type == 'conda'
  #   runs-on: ubuntu-latest

  #   # output:
  #   #   out-id: out.${{ inputs.env-type }}.${{ inputs.hw-type }}

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Test
  #       run: |
  #         echo "env: " ${{ inputs.env-type }}
  #         echo "hw: " ${{ inputs.hw-type }}
  #         ls -la
  #         g++ main.cpp
  build-common:
    name: Build (${{ inputs.env-type }}.${{ inputs.hw-type }})
    runs-on: ubuntu-latest

    # output:
    #   out-id: out.${{ inputs.env-type }}.${{ inputs.hw-type }}

    steps:
      - if: inputs.env-type == 'docker'
        uses: actions/cache@v3
        with:
          path: /tmp/docker-registry
          key: image-cached
          restore-keys: image-cached
      - if: inputs.env-type == 'docker'
        run: |
          DOCKER_OPTS=" -g  /tmp/docker-registry" && sudo systemctl restart docker
          docker pull devjiu/cpu-hdk:check || true
      - run: |
          echo "cache-hit? \"${{ steps.cache.outputs.cache-hit }}\""
      # - if: steps.cache.outputs.cache-hit != 'true' && inputs.env-type == 'docker'
      #   run: |
      #     docker pull devjiu/cpu-hdk:check
      #     cp -r /var/lib/registry /tmp/docker-registry 
      - if: inputs.env-type == 'docker'
        run: |
          docker run -i --name verify\
            -v ${PWD}:/home/hdk \
            -w /home/hdk \
            devjiu/cpu-hdk:check \
            /usr/bin/bash
          docker image ls -a
          docker container ls -a
          docker start verify
          echo "PRE=docker exec verify" >> $GITHUB_ENV

      - uses: actions/checkout@v3

      - run: |
          ${{env.PRE}} echo "env: " ${{ inputs.env-type }}
          ${{env.PRE}} echo "hw: " ${{ inputs.hw-type }}
          ${{env.PRE}} ls -la ../
          ${{env.PRE}} g++ main.cpp

  call-test:
    needs: [build-common]
    strategy:
      matrix:
        test-type: [unit, integration]
    uses: ./.github/workflows/ex_test.yml
    with:
      test-type: ${{ matrix.test-type }}
      env-type: ${{ inputs.env-type }}
      hw-type: ${{ inputs.hw-type }}