name: Build
on:
  workflow_call:
    inputs:
      env-type: 
        required: true
        type: string
        default: None
      hw-type:
        required: true
        type: string
        default: None

jobs:
  # build-docker:
  #   name: Build Docker (${{ inputs.env-type }}.${{ inputs.hw-type }})
  #   if: inputs.env-type == 'docker'
  #   runs-on: ubuntu-latest
  #   container: devjiu/cpu-hdk:check

  #   # output:
  #   #   out-id: out.${{ inputs.env-type }}.${{ inputs.hw-type }}

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Test
  #       run: |
  #         echo "env: " ${{ inputs.env-type }}
  #         echo "hw: " ${{ inputs.hw-type }}
  #         ls -la
  #         g++ main.cpp
  # build-conda: 
  #   name: Build Conda (${{ inputs.env-type }}.${{ inputs.hw-type }})
  #   if: inputs.env-type == 'conda'
  #   runs-on: ubuntu-latest

  #   # output:
  #   #   out-id: out.${{ inputs.env-type }}.${{ inputs.hw-type }}

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Test
  #       run: |
  #         echo "env: " ${{ inputs.env-type }}
  #         echo "hw: " ${{ inputs.hw-type }}
  #         ls -la
  #         g++ main.cpp
  build-common:
    name: Build common (${{ inputs.env-type }}.${{ inputs.hw-type }})
    runs-on: ubuntu-latest

    # output:
    #   out-id: out.${{ inputs.env-type }}.${{ inputs.hw-type }}

    steps:
      - if: inputs.env-type == 'docker'
        uses: docker/build-push-action@v4
        with:
          context: .
          pull: true
          push: false
          tags: "devjiu/cpu-hdk:check"
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - uses: actions/checkout@v3

      - name: Test
        run: |
          echo "env: " ${{ inputs.env-type }}
          echo "hw: " ${{ inputs.hw-type }}
          ls -la
          g++ main.cpp