name: Test
on:
  workflow_call:
    inputs:
      test-type:
        required: true
        type: string
        default: None

jobs:
  test:
    name: Test (${{ input.test-type }})
    runs-on: ubuntu-latest
    #container: devjiu/cpu-hdk:check

    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |
          echo "env: " ${{ matrix.env-type }}
          echo "hw: " ${{ matrix.hw-type }}
          ls -la