name: Test
on:
  workflow_call:
    inputs:
      cuda_compiler_version:
        type: string
        default: None

jobs:
  test:
    name: Test (${{ matrix.env-type }}.${{ matrix.hw-type }}) - ${{ matrix.test-type }}
    runs-on: ubuntu-latest
    container: devjiu/cpu-hdk:check

    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |
          echo "env: " ${{ matrix.env-type }}
          echo "hw: " ${{ matrix.hw-type }}
          ls -la