name: Test
on:
  workflow_call:
    inputs:
      test-type:
        required: true
        type: string
        default: None

jobs:
  test:
    name: Test (${{ inputs.test-type }})
    runs-on: ubuntu-latest
    #container: devjiu/cpu-hdk:check

    steps:
      - name: Test
        run: |
          echo "test: " ${{ inputs.test-type }}
          ls -la