name: Main workflow
on:
  workflow_dispatch:
  push: []
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment-type: [docker, conda]
        hardware-type: [CPU, GPU] #L0
    
    uses: ./.github/workflows/ex.yml
    # steps:
    # - name: Checkout workflows repo # required so we can reference the actions locally
    #   uses: actions/checkout@v3
    # - name: Why
    #   run: ls -lah ./.github/workflows
    # - uses: ./.github/workflows/ex.yml
    #   with: 
    #     env-type: ${{ matrix.environment-type }}
    #     hw-type: ${{ matrix.hardware-type }}
  
  # ref:
  #   uses: ./.github/workflows/ref.yml

  test:
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-type: [unit, integration]
    
    steps:
    - uses: ./.github/workflows/ex_test.yml # name: Test (${{ fromJson(needs.build.strategy.matrix.environment-type) }}.${{ fromJson(needs.build.strategy.matrix.hardware-type) }}) - ${{ matrix.test-type }}
    # - name: Unit tests
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: 12.x
    # - name: Integration tests
    #   run: npm install
    # - name: Style check
    #   run: npm run format-check


# jobs:
#   modin:
#     uses: ./.github/workflows/modin.yml

#   build:
#     uses: ./.github/workflows/build.yml

#   build-cuda:
#     uses: ./.github/workflows/build.yml
#     with:
#       cuda_compiler_version: 11

#   style:
#     needs: build
#     uses: ./.github/workflows/test.yml
#     with:
#       cache-suffix: ${{ needs.build.outputs.cache-suffix }}
#       test: style

