name: Main workflow
on:
  workflow_dispatch:
  push: []
jobs:
  build:
    strategy:
      matrix:
        environment-type: [docker, conda]
        hardware-type: [CPU, GPU] #L0
    uses: ./.github/workflows/ex.yml
    with:
      env-type: ${{ matrix.environment-type }}
      hw-type: ${{ matrix.hardware-type }}
  #   steps:
  #   - name: Test (${{ matrix.test-type }})
  #     if: steps.build.outputs.random-number == 9 #build.${{ matrix.environment-type }}.${{ matrix.hardware-type }}
  #     uses: ./actions/test
  #     with:
  #       env-type: ${{ matrix.environment-type }}
  #       hw-type: ${{ matrix.hardware-type }}
  #       test-type:  ${{ matrix.test-type }}

  # style:
  #   needs: build
  #   uses: ./.github/workflows/test.yml
  #   with:
  #     cache-suffix: ${{ needs.build.outputs.cache-suffix }}
  #     test: style

